### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by filoscoder** [socketio/socket.io-sticky#5]
Hi, 
in my team, I'm following [this](https://socket.io/docs/v4/pm2/) doc to implement the usage of Socket.io server with PM2.

Our project is written in typescript which is complaining regard of the missing types of  `socket.io-sticky`

![Screen Shot 2022-03-04 at 11 33 37](https://user-images.githubusercontent.com/50701501/156747847-435d83ad-27a7-4bbb-a179-fd697a836533.png)

Should we expect support type support any soon?

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-sticky/commit/bab550ba7d4fb796dd3f1ea5c5286e8046996748, included in version [1.0.2](https://github.com/socketio/socket.io-sticky/releases/tag/1.0.2) :rocket:
